# -*- coding: utf-8 -*-
"""AutoML[Re].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UVNOMDwuOjui1kJ4Me4cPe0giv5WF0ZN
"""

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder, LabelEncoder
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

def AutoPipeline(df: pd.DataFrame, target_column: str, text_columns=None):
    if text_columns is None:
        text_columns = []

    X = df.drop(columns=[target_column])
    y = df[target_column]

    # Identify variable types automatically
    numeric_features = X.select_dtypes(include=['int64', 'float64']).columns.tolist()
    categorical_features = X.select_dtypes(include=['object', 'category']).columns.tolist()

    # Filter out explicit text columns from standard categorical handling
    categorical_features = [col for col in categorical_features if col not in text_columns]

    # Define dedicated transformers
    numeric_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='median')),
        ('scaler', StandardScaler())
    ])

    categorical_transformer = Pipeline(steps=[
        ('imputer', SimpleImputer(strategy='most_frequent')),
        ('onehot', OneHotEncoder(handle_unknown='ignore', sparse_output=False))
    ])

    # Assemble transformers dynamically using ColumnTransformer
    transformer_list = []
    if numeric_features:
        transformer_list.append(('num', numeric_transformer, numeric_features))
    if categorical_features:
        transformer_list.append(('cat', categorical_transformer, categorical_features))

    for text_col in text_columns:
        transformer_list.append((f'text_{text_col}', TfidfVectorizer(max_features=100), text_col))

    preprocessor = ColumnTransformer(transformers=transformer_list, remainder='drop')

    # Determine task type
    if y.dtype == 'object' or len(np.unique(y)) < 10:
        task_type = "classification"
        # Encode target if categorical
        if y.dtype == 'object':
            y = pd.Series(LabelEncoder().fit_transform(y), index=y.index)
    else:
        task_type = "regression"

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    return preprocessor, X_train, X_test, y_train, y_test, task_type

import joblib
import numpy as np
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score, r2_score
import tensorflow as tf

def train_best_model(preprocessor, X_train, X_test, y_train, y_test, task_type: str, output_dir="/tmp"):
    """
    Executes a grid search across Scikit-learn models and tests a fallback TensorFlow NN.
    Saves the absolute best performing model to disk.
    """
    # Transform raw data through our dynamic preprocessor
    X_train_trans = preprocessor.fit_transform(X_train)
    X_test_trans = preprocessor.transform(X_test)

    input_dim = X_train_trans.shape[1]
    best_score = -float('inf')
    best_model_artifact = None
    model_tech = "sklearn"
    metrics = {}

    if task_type == "classification":
        # Candidate 1: Random Forest Grid Search
        rf = RandomForestClassifier(random_state=42)
        param_grid = {'n_estimators': [50, 100], 'max_depth': [5, 10]}
        grid = GridSearchCV(rf, param_grid, cv=3, scoring='accuracy')
        grid.fit(X_train_trans, y_train)

        rf_preds = grid.best_estimator_.predict(X_test_trans)
        rf_acc = accuracy_score(y_test, rf_preds)

        metrics["RandomForest_Accuracy"] = float(rf_acc)
        best_score = rf_acc
        best_model_artifact = grid.best_estimator__

    else:
        # Candidate 2: Regression Suite
        reg = RandomForestRegressor(random_state=42)
        param_grid = {'n_estimators': [50, 100]}
        grid = GridSearchCV(reg, param_grid, cv=3, scoring='r2')
        grid.fit(X_train_trans, y_train)

        reg_preds = grid.best_estimator_.predict(X_test_trans)
        reg_r2 = r2_score(y_test, reg_preds)

        metrics["RandomForest_R2"] = float(reg_r2)
        best_score = reg_r2
        best_model_artifact = grid.best_estimator_

    # Fallback Option: Neural Network via TensorFlow Keras
    # (Exemplifying a highly adaptable MLP implementation)
    nn_model = tf.keras.Sequential([
        tf.keras.layers.Input(shape=(input_dim,)),
        tf.keras.layers.Dense(32, activation='relu'),
        tf.keras.layers.Dropout(0.2),
        tf.keras.layers.Dense(1 if task_type == "regression" else len(np.unique(y_train)),
                              activation='linear' if task_type == "regression" else 'softmax')
    ])

    loss_fn = 'mse' if task_type == "regression" else 'sparse_categorical_crossentropy'
    optimizer_algo = tf.keras.optimizers.Adam(learning_rate=0.01)
    nn_model.compile(optimizer=optimizer_algo, loss=loss_fn, metrics=['accuracy' if task_type == "classification" else 'mae'])

    # Train the neural network
    nn_model.fit(X_train_trans, y_train, epochs=10, batch_size=32, verbose=0)

    # Evaluate TensorFlow performance
    nn_eval = nn_model.evaluate(X_test_trans, y_test, verbose=0)

    if task_type == "classification":
        metrics["TensorFlow_Accuracy"] = float(nn_eval[1])
        if nn_eval[1] > best_score:
            best_score = nn_eval[1]
            best_model_artifact = nn_model
            model_tech = "tensorflow"
    else:
        # For simplicity of metric ranking, inverse of MAE can be mapped or tracked directly
        metrics["TensorFlow_MAE"] = float(nn_eval[1])

    # Package whole pipeline (Preprocessing + Model Estimator) for true portability
    model_path = f"{output_dir}/model"
    if model_tech == "sklearn":
        export_pipeline = Pipeline([('preprocessor', preprocessor), ('estimator', best_model_artifact)])
        model_path += ".pkl"
        joblib.dump(export_pipeline, model_path)
    else:
        # For mixed deployment environments, save structural weights separate from preprocessor object
        model_path += ".h5"
        best_model_artifact.save(model_path)
        joblib.dump(preprocessor, f"{output_dir}/preprocessor.pkl")

    return metrics, model_path, model_tech

from fastapi import FastAPI, UploadFile, File, Form
from fastapi.responses import FileResponse
import pandas as pd
import json
import os

app = FastAPI(title="Auto-Streamline API", version="1.0.0")

@app.post("/api/v1/train")
async def run_automl_pipeline(
    file: UploadFile = File(...),
    target: str = Form(...),
    text_cols: str = Form("[]")  # Expected as serialized JSON array
):
    try:
        text_columns_parsed = json.loads(text_cols)

        # Read incoming data stream completely into RAM safely
        df = pd.read_csv(file.file)

        if target not in df.columns:
            return {"error": f"Target column '{target}' not present in provided file artifact."}

        # Trigger the automatic preprocessing step
        preprocessor, X_train, X_test, y_train, y_test, task_type = AutoPipeline(
            df, target_column=target, text_columns=text_columns_parsed
        )

        # Run training loop execution
        metrics, model_path, tech = train_best_model(
            preprocessor, X_train, X_test, y_train, y_test, task_type, output_dir="/tmp"
        )

        return {
            "status": "Success",
            "task_type": task_type,
            "chosen_framework": tech,
            "evaluation_metrics": metrics,
            "download_route": f"/api/v1/download?path={model_path}"
        }
    except Exception as e:
        return {"status": "Error", "detail": str(e)}

@app.get("/api/v1/download")
def download_model(path: str):
    if os.path.exists(path):
        return FileResponse(path=path, filename=os.path.basename(path), media_type='application/octet-stream')
    return {"error": "File artifact could not be resolved on local disk path."}